[platformio]
default_envs = nanoatmega328
src_dir = Altair_Satellite_02_Packet_Counter_TX

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 115200
lib_deps =
    jgromes/RadioLib@7.7.1
