[platformio]
default_envs = bluepill_f103c8
src_dir = Altair_Satellite_STM32

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
monitor_speed = 115200
lib_deps =
    jgromes/RadioLib@7.7.1
build_flags =
    -fpermissive
